# Site wide configuration (available as site.variable_name)
title: gyatso
description: 'a minimalist Jekyll theme'
url: https://www.lakshitabhargava/gyatso
author: Ankur Gupta

# Owner configuration
# (leave blank to disable the corresponding sharing button)
owner:
  github: ankur-gupta
  twitter: ankurIO
  linkedin: ankurguptawisc

attribution:
  theme_name: Lagrange
  theme_url: https://lenpaul.github.io/Lagrange/

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'laplacian'

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 3

# Markdown
markdown: kramdown
highlighter: rouge

# Gems
plugins: ['jekyll-paginate']

# Exclude
exclude: ['README.md']

# Additional collections
# https://jekyllrb.com/docs/collections/
collections:
  bites:
    output: true
    permalink: /:collection/:year/:month/:day/:title

# Additional collections
# https://jekyllrb.com/docs/collections/
collections:
  books:
    output: true
    permalink: /:collection/:year/:month/:day/:title
